development:
  adapter: postgresql
  encoding: unicode
  database: launchipsum_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: launchipsum_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: launchipsum_production
  pool: 5
  username:
  password:
